version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es-ml-demo
    environment:
      - node.name=es-ml-demo
      - cluster.name=es-ml-demo-cluster
      - discovery.type=single-node
      # włączamy ML
      - xpack.ml.enabled=true
      # włączamy trial żeby ML działał
      - xpack.license.self_generated.type=trial
      # na potrzeby demo wyłączamy security
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    ports:
#      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana-ml-demo
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_REQUESTTIMEOUT=90000
      # na potrzeby demo bez security
      - XPACK_SECURITY_ENABLED=false
      - SERVER_HOST=0.0.0.0
    ports:
      - "5601:5601"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.0
    container_name: metricbeat-ml-demo
    depends_on:
      - elasticsearch
      - kibana
    user: root
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: ["--strict.perms=false"]
    restart: unless-stopped

volumes:
  esdata:
